# fly.toml app configuration file generated for bold-cherry-3659 on 2023-10-25T12:33:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-cherry-3659"
primary_region = "sea"

[[services]]
  http_checks = []
  internal_port = 8043
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443